---
- hosts: all
  gather_facts: true
  become_method: sudo
  become_user: root
  tasks:
    - name: Install Apache
      yum:
        name: httpd
        state: latest

    - name: Configure index.html
      template: src=./index.j2 dest=/var/www/html/index.html

    - name: Restart Apache
      service:
        name: httpd
        state: restarted

    - name: Cofigure firewalld
      firewalld:
        service: http
        permanent: true
        state: enabled
