---
- hosts: all
  gather_facts: true
  become_method: sudo
  become_user: root
  tasks:
    - name: Install Apache
      yum:
        name: httpd
        state: latest

    - name: Install Hello World
      copy: src=index.html dest=/var/www/index.html
